"""Add subscription_start end

Revision ID: 15a088e3ed83
Revises: c1c77aeb5ba9
Create Date: 2025-05-27 18:41:00.129299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a088e3ed83'
down_revision: Union[str, None] = 'c1c77aeb5ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_start', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_id')
    op.drop_column('users', 'subscription_end')
    op.drop_column('users', 'subscription_start')
    # ### end Alembic commands ###
