"""Add video_generation_count and last_video_reset to users

Revision ID: 6fdbf3b24012
Revises: 8d0f1d0769e6
Create Date: 2025-05-24 17:52:15.015671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdbf3b24012'
down_revision: Union[str, None] = '8d0f1d0769e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('video_generation_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_video_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_video_reset')
    op.drop_column('users', 'video_generation_count')
    # ### end Alembic commands ###
