"""Add subscription_number

Revision ID: c1c77aeb5ba9
Revises: 6fdbf3b24012
Create Date: 2025-05-27 03:38:33.453622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c77aeb5ba9'
down_revision: Union[str, None] = '6fdbf3b24012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_type',
               existing_type=postgresql.ENUM('free', 'premium', 'pro', name='subscription_type'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_type',
               existing_type=postgresql.ENUM('free', 'premium', 'pro', name='subscription_type'),
               nullable=True)
    # ### end Alembic commands ###
